### ISSUE TITLE
When ImageView Animates overlapping，PeriscopeLayout will overdraw。

### ISSUE THREAD

**Issue by garrickjubiao** [AlanCheen/PeriscopeLayout#3]
存在过度绘制导致界面卡顿问题。
快速点击PeriscopeLayout区域，大量的爱心图片做动画发送重叠后，打开GPU Overdraw检测到过度绘制。

**Comment by czn6** [comment]
想了一下 没什么好办法，太复杂了。
有好的解决方案么？
